### PR TITLE
Multiple Issue Fixes - #7, #42 + #44

### PR DESCRIPTION
**Pull request by simonsigre**
Resolves: 
https://github.com/PaloAltoNetworks/Splunk_TA_paloalto/issues/7
https://github.com/PaloAltoNetworks/Splunk_TA_paloalto/issues/42
https://github.com/PaloAltoNetworks/Splunk_TA_paloalto/issues/44

## How Has This Been Tested?
Fixes have been deployed at a number of customers for quite some time

## Types of changes
Detailed in issues:
- Bug fix (non-breaking change which fixes an issue)
https://github.com/PaloAltoNetworks/Splunk_TA_paloalto/issues/7
https://github.com/PaloAltoNetworks/Splunk_TA_paloalto/issues/42
https://github.com/PaloAltoNetworks/Splunk_TA_paloalto/issues/44

### CODE REVIEW

**Comment by simonsigre** [comment]
@paulmnguyen is this ever going to happen?

**Comment by btorresgil** [comment]
@simonsigre Thanks for this PR. There’s a lot here and it conflicts with some in-flight work to support GP in PAN-OS 9.1. We’re trying to get this tested and merged but with current circumstances it has taken a while. Thanks for your patience!

**Comment by simonsigre** [comment]
Our team is very able to assist as we have a number of customers using a number of OS versions and hardware chassis.
I’d be lying if I said it’s not a tad frustrating given the project is “open” but work is happening behind scenes ... is there anything partners (such as us) of both Palo and Splunk can do to try and align our work?
Is there a close beta ?

**Comment by btorresgil** [comment]
@simonsigre I'm interested in getting customers and partners more involved. Let's discuss. Can you ping us at splunkapp@paloaltonetworks.com to set up a time to chat?

**Pull request closed without merging**
